# Ports collection makefile for:    isc-dhcp41-client
# Date created:         28 March 2010
# Whom:                 Wesley Shields <wxs@FreeBSD.org>
#
# $FreeBSD: head/net/isc-dhcp41-client/Makefile 300897 2012-07-14 14:29:18Z beat $
#

COMMENT=	The ISC Dynamic Host Configuration Protocol client

SUBSYS=		client
MASTERDIR=	${.CURDIR}/../isc-dhcp41-server

.include "${MASTERDIR}/Makefile"
